package driver

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

func TestCargoLocalPackages(t *testing.T) {
	root := t.TempDir()
	lock := `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "workspace-member"
version = "0.1.0"
dependencies = [
 "regex",
]

[[package]]
name = "regex"
version = "1.10.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"

[[package]]
name = "path-dep"
version = "0.2.0"
dependencies = []
`
	if err := os.WriteFile(filepath.Join(root, "Cargo.lock"), []byte(lock), 0o644); err != nil {
		t.Fatal(err)
	}

	home := t.TempDir()
	t.Setenv("CARGO_HOME", home)

	d := cargoDriver{}
	entries, err := d.LocalPackages(context.Background(), root)
	if err != nil {
		t.Fatalf("LocalPackages: %v", err)
	}

	// workspace-member and path-dep have no "source" line (they're not
	// fetched from a registry), so only regex should be reported.
	if len(entries) != 1 {
		t.Fatalf("got %d entries, want 1: %+v", len(entries), entries)
	}
	if entries[0].Name != "regex" || entries[0].Version != "1.10.2" {
		t.Errorf("got %+v, want name=regex version=1.10.2", entries[0])
	}
	if entries[0].Kind != KindLocalPackage {
		t.Errorf("got Kind=%v, want KindLocalPackage", entries[0].Kind)
	}
}

func TestCargoLocalPackagesNoLockfile(t *testing.T) {
	root := t.TempDir()
	d := cargoDriver{}
	entries, err := d.LocalPackages(context.Background(), root)
	if err != nil {
		t.Fatalf("LocalPackages: %v", err)
	}
	if entries != nil {
		t.Errorf("got %+v, want nil", entries)
	}
}

func TestParseCargoInstallList(t *testing.T) {
	binDir := t.TempDir()
	rgPath := filepath.Join(binDir, "rg")
	if err := os.WriteFile(rgPath, []byte("fake binary contents"), 0o755); err != nil {
		t.Fatal(err)
	}
	// dlv is listed but missing from binDir, so it should size as -1.

	out := "ripgrep v13.0.0:\n    rg\ndelve v1.27.1:\n    dlv\n"
	entries := parseCargoInstallList([]byte(out), binDir)

	if len(entries) != 2 {
		t.Fatalf("got %d entries, want 2: %+v", len(entries), entries)
	}

	if entries[0].Name != "ripgrep" || entries[0].Version != "13.0.0" {
		t.Errorf("got %+v, want name=ripgrep version=13.0.0", entries[0])
	}
	wantSize, err := os.Stat(rgPath)
	if err != nil {
		t.Fatal(err)
	}
	if entries[0].Size != wantSize.Size() {
		t.Errorf("got Size=%d, want %d", entries[0].Size, wantSize.Size())
	}

	if entries[1].Name != "delve" || entries[1].Version != "1.27.1" {
		t.Errorf("got %+v, want name=delve version=1.27.1", entries[1])
	}
	if entries[1].Size != -1 {
		t.Errorf("got Size=%d, want -1 for missing binary", entries[1].Size)
	}
}

func TestParseCargoInstallListExeFallback(t *testing.T) {
	binDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(binDir, "dlv.exe"), []byte("fake"), 0o755); err != nil {
		t.Fatal(err)
	}

	out := "delve v1.27.1:\n    dlv\n"
	entries := parseCargoInstallList([]byte(out), binDir)

	if len(entries) != 1 {
		t.Fatalf("got %d entries, want 1: %+v", len(entries), entries)
	}
	if entries[0].Size != 4 {
		t.Errorf("got Size=%d, want 4 (matched via .exe fallback)", entries[0].Size)
	}
}

func TestCargoToolchainEntries(t *testing.T) {
	rustupHomeDir := t.TempDir()
	t.Setenv("RUSTUP_HOME", rustupHomeDir)

	toolchainsDir := filepath.Join(rustupHomeDir, "toolchains", "stable-x86_64-pc-windows-msvc")
	if err := os.MkdirAll(toolchainsDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(toolchainsDir, "bin"), []byte("fake"), 0o644); err != nil {
		t.Fatal(err)
	}

	entries := cargoToolchainEntries(context.Background())
	if len(entries) != 1 {
		t.Fatalf("got %d entries, want 1: %+v", len(entries), entries)
	}
	if entries[0].Name != "stable-x86_64-pc-windows-msvc" {
		t.Errorf("got Name=%q, want stable-x86_64-pc-windows-msvc", entries[0].Name)
	}
	if entries[0].Kind != KindToolchain {
		t.Errorf("got Kind=%v, want KindToolchain", entries[0].Kind)
	}
}

func TestCargoToolchainEntriesNoRustup(t *testing.T) {
	t.Setenv("RUSTUP_HOME", filepath.Join(t.TempDir(), "does-not-exist"))

	entries := cargoToolchainEntries(context.Background())
	if entries != nil {
		t.Errorf("got %+v, want nil", entries)
	}
}

func TestCargoLocalInstallDir(t *testing.T) {
	d := cargoDriver{}
	if dir, ok := d.LocalInstallDir("/some/project"); ok || dir != "" {
		t.Errorf("got (%q, %v), want (\"\", false)", dir, ok)
	}
}
