package driver

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

func TestCargoLocalPackages(t *testing.T) {
	root := t.TempDir()
	lock := `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "workspace-member"
version = "0.1.0"
dependencies = [
 "regex",
]

[[package]]
name = "regex"
version = "1.10.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"

[[package]]
name = "path-dep"
version = "0.2.0"
dependencies = []
`
	if err := os.WriteFile(filepath.Join(root, "Cargo.lock"), []byte(lock), 0o644); err != nil {
		t.Fatal(err)
	}

	home := t.TempDir()
	t.Setenv("CARGO_HOME", home)

	d := cargoDriver{}
	entries, err := d.LocalPackages(context.Background(), root)
	if err != nil {
		t.Fatalf("LocalPackages: %v", err)
	}

	// workspace-member and path-dep have no "source" line (they're not
	// fetched from a registry), so only regex should be reported.
	if len(entries) != 1 {
		t.Fatalf("got %d entries, want 1: %+v", len(entries), entries)
	}
	if entries[0].Name != "regex" || entries[0].Version != "1.10.2" {
		t.Errorf("got %+v, want name=regex version=1.10.2", entries[0])
	}
	if entries[0].Kind != KindLocalPackage {
		t.Errorf("got Kind=%v, want KindLocalPackage", entries[0].Kind)
	}
}

func TestCargoLocalPackagesNoLockfile(t *testing.T) {
	root := t.TempDir()
	d := cargoDriver{}
	entries, err := d.LocalPackages(context.Background(), root)
	if err != nil {
		t.Fatalf("LocalPackages: %v", err)
	}
	if entries != nil {
		t.Errorf("got %+v, want nil", entries)
	}
}

func TestCargoLocalInstallDir(t *testing.T) {
	d := cargoDriver{}
	if dir, ok := d.LocalInstallDir("/some/project"); ok || dir != "" {
		t.Errorf("got (%q, %v), want (\"\", false)", dir, ok)
	}
}
