package driver

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/ro80t/cacheriff/internal/platform"
	"github.com/ro80t/cacheriff/internal/textwrap"
)

type denoDriver struct {
	base
}

func NewDenoDriver() Driver {
	// localDir is left unset: see LocalPackages for why.
	return denoDriver{base: base{
		id:          "deno",
		name:        "Deno",
		binary:      "deno",
		supportedOS: []platform.OS{platform.Windows, platform.MacOS, platform.Linux},
		dirs:        []string{"node_modules"},
	}}
}

// denoInfo is the subset of `deno info --json`'s (no-script-argument
// form) fields that name its cache directories.
type denoInfo struct {
	DenoDir         string `json:"denoDir"`
	ModulesCache    string `json:"modulesCache"`
	NpmCache        string `json:"npmCache"`
	TypescriptCache string `json:"typescriptCache"`
	RegistryCache   string `json:"registryCache"`
}

func fetchDenoInfo(ctx context.Context) (denoInfo, error) {
	out, err := exec.CommandContext(ctx, "deno", "info", "--json").Output()
	if err != nil {
		return denoInfo{}, fmt.Errorf("deno info --json: %w", err)
	}
	var info denoInfo
	if err := json.Unmarshal(out, &info); err != nil {
		return denoInfo{}, fmt.Errorf("deno info --json: parse output: %w", err)
	}
	return info, nil
}

func (d denoDriver) CacheDir(ctx context.Context) (string, error) {
	info, err := fetchDenoInfo(ctx)
	if err != nil {
		return "", err
	}
	return info.DenoDir, nil
}

func (d denoDriver) CacheEntries(ctx context.Context) ([]Entry, error) {
	info, err := fetchDenoInfo(ctx)
	if err != nil {
		return nil, err
	}
	return denoCacheEntriesFromInfo(ctx, info), nil
}

func denoCacheEntriesFromInfo(ctx context.Context, info denoInfo) []Entry {
	return sizeCacheDirs(ctx, []namedDir{
		{"Remote module cache", info.ModulesCache},
		{"npm package cache", info.NpmCache},
		{"TypeScript compile cache", info.TypescriptCache},
		{"JSR/registry cache", info.RegistryCache},
	})
}

func denoInstallRoot() (string, error) {
	if v := os.Getenv("DENO_INSTALL_ROOT"); v != "" {
		return v, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("deno: resolve home directory: %w", err)
	}
	return filepath.Join(home, ".deno"), nil
}

func (d denoDriver) GlobalInstallDir(_ context.Context) (string, error) {
	root, err := denoInstallRoot()
	if err != nil {
		return "", err
	}
	return filepath.Join(root, "bin"), nil
}

// denoShimSpecRe pulls the target specifier out of a shim script
// generated by `deno install -g`, e.g. (POSIX shell form):
//
//	deno "run" "--allow-all" "--config" "...deno.json" "npm:cowsay" "$@"
//
// or (Windows .cmd form):
//
//	@deno "run" "--allow-all" "--config" "...deno.json" "npm:cowsay" %*
//
// The specifier is always the last quoted argument before "$@"/%*.
var denoShimSpecRe = regexp.MustCompile(`"([^"]+)"\s+(?:"\$@"|%\*)\s*$`)

// GlobalPackages is best-effort: deno has no command that lists
// installed CLI tools with resolved versions, so this scans the bin
// directory's generated shim scripts and reports each one's target
// specifier (e.g. "npm:cowsay") as the Version.
func (d denoDriver) GlobalPackages(ctx context.Context) ([]Entry, error) {
	binDir, err := d.GlobalInstallDir(ctx)
	if err != nil {
		return nil, err
	}
	entries, err := readDenoShims(binDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	return entries, nil
}

func readDenoShims(binDir string) ([]Entry, error) {
	dirEntries, err := os.ReadDir(binDir)
	if err != nil {
		return nil, err
	}

	var entries []Entry
	seen := make(map[string]bool)
	for _, de := range dirEntries {
		if de.IsDir() {
			continue
		}
		name := de.Name()
		if name == "deno" || name == "deno.exe" {
			continue
		}
		base := strings.TrimSuffix(strings.TrimSuffix(name, ".cmd"), ".ps1")
		if seen[base] {
			continue
		}

		data, err := os.ReadFile(filepath.Join(binDir, name))
		if err != nil {
			continue
		}
		if !strings.Contains(string(data), "generated by deno install") {
			continue // not a deno-managed shim
		}
		seen[base] = true

		version := ""
		if m := denoShimSpecRe.FindStringSubmatch(string(data)); m != nil {
			version = m[1]
		}
		entries = append(entries, Entry{
			Name:    base,
			Version: version,
			Path:    filepath.Join(binDir, name),
			Kind:    KindGlobalPackage,
			Size:    -1,
		})
	}
	return entries, nil
}

// LocalPackages always reports nothing: unlike npm/yarn/pnpm/bun,
// Deno resolves dependencies into the shared DENO_DIR cache (already
// covered by CacheEntries) rather than copying them into the project.
func (denoDriver) LocalPackages(_ context.Context, _ string) ([]Entry, error) {
	return nil, nil
}

func (d denoDriver) Remove(ctx context.Context, e Entry) error {
	switch e.Kind {
	case KindCache:
		return os.RemoveAll(e.Path)
	case KindGlobalPackage:
		name, err := textwrap.EscapeArg(e.Name)
		if err != nil {
			return fmt.Errorf("deno: %w", err)
		}
		return d.runCombined(ctx, "uninstall", "-g", name)
	default:
		return d.unsupportedKindErr(e.Kind)
	}
}
