package driver

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"sync"

	"cacheriff/internal/platform"
)

type denoDriver struct {
	base
}

// NewDenoDriver returns the Driver for Deno.
func NewDenoDriver() Driver {
	return denoDriver{base: base{
		id:          "deno",
		name:        "Deno",
		binary:      "deno",
		supportedOS: []platform.OS{platform.Windows, platform.MacOS, platform.Linux},
		dirs:        []string{"node_modules"},
	}}
}

// denoInfo is the subset of `deno info --json`'s (no-script-argument
// form) fields that name its cache directories.
type denoInfo struct {
	DenoDir         string `json:"denoDir"`
	ModulesCache    string `json:"modulesCache"`
	NpmCache        string `json:"npmCache"`
	TypescriptCache string `json:"typescriptCache"`
	RegistryCache   string `json:"registryCache"`
}

func fetchDenoInfo(ctx context.Context) (denoInfo, error) {
	out, err := exec.CommandContext(ctx, "deno", "info", "--json").Output()
	if err != nil {
		return denoInfo{}, fmt.Errorf("deno info --json: %w", err)
	}
	var info denoInfo
	if err := json.Unmarshal(out, &info); err != nil {
		return denoInfo{}, fmt.Errorf("deno info --json: parse output: %w", err)
	}
	return info, nil
}

func (d denoDriver) CacheDir(ctx context.Context) (string, error) {
	info, err := fetchDenoInfo(ctx)
	if err != nil {
		return "", err
	}
	return info.DenoDir, nil
}

func (d denoDriver) CacheEntries(ctx context.Context) ([]Entry, error) {
	info, err := fetchDenoInfo(ctx)
	if err != nil {
		return nil, err
	}
	return denoCacheEntriesFromInfo(ctx, info), nil
}

func denoCacheEntriesFromInfo(ctx context.Context, info denoInfo) []Entry {
	dirs := []struct{ name, path string }{
		{"Remote module cache", info.ModulesCache},
		{"npm package cache", info.NpmCache},
		{"TypeScript compile cache", info.TypescriptCache},
		{"JSR/registry cache", info.RegistryCache},
	}

	// A long-lived DENO_DIR (especially the remote module cache) can
	// accumulate a lot of files, so size these concurrently rather
	// than paying for each walk one after another - the same
	// treatment CacheEntries gets for cargo and go.
	entries := make([]Entry, len(dirs))
	present := make([]bool, len(dirs))
	var wg sync.WaitGroup
	for i, dd := range dirs {
		if dd.path == "" || !pathExists(dd.path) {
			continue
		}
		present[i] = true
		wg.Add(1)
		go func(i int, name, path string) {
			defer wg.Done()
			size, err := dirSize(ctx, path)
			if err != nil {
				size = -1
			}
			entries[i] = Entry{
				Name: name,
				Path: path,
				Kind: KindCache,
				Size: size,
			}
		}(i, dd.name, dd.path)
	}
	wg.Wait()

	result := make([]Entry, 0, len(entries))
	for i, e := range entries {
		if present[i] {
			result = append(result, e)
		}
	}
	return result
}

func denoInstallRoot() (string, error) {
	if v := os.Getenv("DENO_INSTALL_ROOT"); v != "" {
		return v, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("deno: resolve home directory: %w", err)
	}
	return filepath.Join(home, ".deno"), nil
}

func (d denoDriver) GlobalInstallDir(_ context.Context) (string, error) {
	root, err := denoInstallRoot()
	if err != nil {
		return "", err
	}
	return filepath.Join(root, "bin"), nil
}

// denoShimSpecRe pulls the target specifier out of a shim script
// generated by `deno install -g`, e.g. (POSIX shell form):
//
//	deno "run" "--allow-all" "--config" "...deno.json" "npm:cowsay" "$@"
//
// or (Windows .cmd form):
//
//	@deno "run" "--allow-all" "--config" "...deno.json" "npm:cowsay" %*
//
// The specifier is always the last quoted argument before "$@"/%*.
var denoShimSpecRe = regexp.MustCompile(`"([^"]+)"\s+(?:"\$@"|%\*)\s*$`)

// GlobalPackages reports the CLI tools installed via `deno install
// -g`, best-effort: deno has no single command that lists them with
// resolved versions, so this scans the bin directory's generated shim
// scripts and pulls out the specifier (e.g. "npm:cowsay" or
// "jsr:@std/foo@1.2.3") each one runs, reporting that as the Version
// since it's the most useful thing deno itself records about it.
func (d denoDriver) GlobalPackages(ctx context.Context) ([]Entry, error) {
	binDir, err := d.GlobalInstallDir(ctx)
	if err != nil {
		return nil, err
	}
	entries, err := readDenoShims(binDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	return entries, nil
}

func readDenoShims(binDir string) ([]Entry, error) {
	dirEntries, err := os.ReadDir(binDir)
	if err != nil {
		return nil, err
	}

	var entries []Entry
	seen := make(map[string]bool)
	for _, de := range dirEntries {
		if de.IsDir() {
			continue
		}
		name := de.Name()
		if name == "deno" || name == "deno.exe" {
			continue
		}
		base := strings.TrimSuffix(strings.TrimSuffix(name, ".cmd"), ".ps1")
		if seen[base] {
			continue
		}

		data, err := os.ReadFile(filepath.Join(binDir, name))
		if err != nil {
			continue
		}
		if !strings.Contains(string(data), "generated by deno install") {
			continue // not a deno-managed shim
		}
		seen[base] = true

		version := ""
		if m := denoShimSpecRe.FindStringSubmatch(string(data)); m != nil {
			version = m[1]
		}
		entries = append(entries, Entry{
			Name:    base,
			Version: version,
			Path:    filepath.Join(binDir, name),
			Kind:    KindGlobalPackage,
			Size:    -1,
		})
	}
	return entries, nil
}

// LocalInstallDir reports that Deno has no per-project package
// install directory: unlike npm/yarn/pnpm/bun, Deno resolves
// dependencies (whether from JSR, npm, or URLs) into its single
// shared, machine-wide DENO_DIR cache (already covered by
// CacheEntries) rather than copying them into the project, much like
// cargo's shared registry.
func (denoDriver) LocalInstallDir(_ string) (string, bool) {
	return "", false
}

// LocalPackages always reports nothing: see LocalInstallDir. A
// project's deno.json can declare an "imports" map, but those are
// version ranges resolved into the shared DENO_DIR cache, not a
// distinct per-project artifact this driver could report a path or
// size for.
func (denoDriver) LocalPackages(_ context.Context, _ string) ([]Entry, error) {
	return nil, nil
}

func (denoDriver) Remove(ctx context.Context, e Entry) error {
	switch e.Kind {
	case KindCache:
		return os.RemoveAll(e.Path)
	case KindGlobalPackage:
		out, err := exec.CommandContext(ctx, "deno", "uninstall", "-g", e.Name).CombinedOutput()
		if err != nil {
			return fmt.Errorf("deno uninstall -g %s: %w: %s", e.Name, err, strings.TrimSpace(string(out)))
		}
		return nil
	default:
		return fmt.Errorf("deno: unsupported entry kind %s", e.Kind)
	}
}
