package driver

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

func TestDenoCacheEntriesFromInfo(t *testing.T) {
	dir := t.TempDir()
	modules := filepath.Join(dir, "remote")
	if err := os.MkdirAll(modules, 0o755); err != nil {
		t.Fatal(err)
	}
	// npmCache deliberately left pointing at a path that doesn't
	// exist, to make sure missing cache dirs are skipped rather than
	// reported with a bogus size.
	info := denoInfo{
		DenoDir:      dir,
		ModulesCache: modules,
		NpmCache:     filepath.Join(dir, "npm-does-not-exist"),
	}

	entries := denoCacheEntriesFromInfo(context.Background(), info)
	if len(entries) != 1 {
		t.Fatalf("got %d entries, want 1: %+v", len(entries), entries)
	}
	if entries[0].Path != modules {
		t.Errorf("got Path=%q, want %q", entries[0].Path, modules)
	}
	if entries[0].Kind != KindCache {
		t.Errorf("got Kind=%v, want KindCache", entries[0].Kind)
	}
}

func TestReadDenoShims(t *testing.T) {
	dir := t.TempDir()

	// The deno binary itself shouldn't be reported as a package.
	if err := os.WriteFile(filepath.Join(dir, "deno.exe"), []byte("not a shim"), 0o755); err != nil {
		t.Fatal(err)
	}

	shim := "#!/bin/sh\n# generated by deno install\n" +
		`deno "run" "--allow-all" "--config" "C:\Users\me\.deno\bin\.cowsay-test\deno.json" "npm:cowsay" "$@"` + "\n"
	if err := os.WriteFile(filepath.Join(dir, "cowsay-test"), []byte(shim), 0o755); err != nil {
		t.Fatal(err)
	}
	cmdShim := "% generated by deno install %\n" +
		`@deno "run" "--allow-all" "--config" "C:\Users\me\.deno\bin\.cowsay-test\deno.json" "npm:cowsay" %*` + "\n"
	if err := os.WriteFile(filepath.Join(dir, "cowsay-test.cmd"), []byte(cmdShim), 0o644); err != nil {
		t.Fatal(err)
	}

	// The per-tool hidden config directory shouldn't be picked up as
	// a file entry (it's a directory).
	if err := os.MkdirAll(filepath.Join(dir, ".cowsay-test"), 0o755); err != nil {
		t.Fatal(err)
	}

	entries, err := readDenoShims(dir)
	if err != nil {
		t.Fatalf("readDenoShims: %v", err)
	}
	if len(entries) != 1 {
		t.Fatalf("got %d entries, want 1 (deduped across cowsay-test and cowsay-test.cmd): %+v", len(entries), entries)
	}
	if entries[0].Name != "cowsay-test" {
		t.Errorf("got Name=%q, want cowsay-test", entries[0].Name)
	}
	if entries[0].Version != "npm:cowsay" {
		t.Errorf("got Version=%q, want npm:cowsay", entries[0].Version)
	}
}

func TestReadDenoShimsIgnoresNonShimFiles(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "notes.txt"), []byte("hello"), 0o644); err != nil {
		t.Fatal(err)
	}

	entries, err := readDenoShims(dir)
	if err != nil {
		t.Fatalf("readDenoShims: %v", err)
	}
	if entries != nil {
		t.Errorf("got %+v, want nil", entries)
	}
}
